#@ load("@ytt:data", "data")

apiVersion: kbld.k14s.io/v1alpha1
kind: ImageOverrides
overrides:
- image: k8s.gcr.io/redis:e2e
  newImage: redis:3.2.9 #! Use same redis version as one used for redis-slave
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: gcr.io/google-samples/gb-frontend:v4
  path: frontend
- image: gcr.io/google_samples/gb-redisslave:v1
  path: redis-slave

#@ if/end data.values.push_images:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: gcr.io/google-samples/gb-frontend:v4
  newImage: #@ data.values.push_images_repo + "/kbld-gb-frontend"
- image: gcr.io/google_samples/gb-redisslave:v1
  newImage: #@ data.values.push_images_repo + "/kbld-gb-redisslave"
