#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if data.values.katacoda:

#! Configure all Deployment resources to use master node
#! since kbld uses local Docker daemon to build images,
#! we will have to use single node (master) for running all Pods

#@overlay/match by=overlay.subset({"kind":"Deployment"}),expects="1+"
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      nodeSelector:
        node-role.kubernetes.io/master: ""

#! Remove ImageDestinations as we do not want to docker login
#! in Katacoda environments to avoid using real credentials
#! in a temporary environment

#@ if data.values.push_images:
#@overlay/match by=overlay.subset({"kind":"ImageDestinations"})
#@overlay/remove
---
#@ end

#! Configure frontend Service to be exposed over a node port,
#! so that it could be visible through Katacoda port view.
#! Available under: "+"" button next to "Terminal Host 1" tab, then
#! click on "Select port to view on Host 1" and enter 30000

#@overlay/match by=overlay.subset({"kind":"Service","metadata":{"name":"frontend"}})
---
spec:
  #@overlay/match missing_ok=True
  type: NodePort
  ports:
  #@overlay/match by="port"
  - port: #@ 80
    #@overlay/match missing_ok=True
    nodePort: 30000

#@ end
